apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      name: notes-pod
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: thatgeekcontainer/notes-app-k8s:latest
          ports:
            - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
spec:
  selector:
    app: notes-app
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: ClusterIP